{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Duration per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_sum[1m]) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Total number of HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Monitored Targets/Sites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "monitored_targets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Cleaned per GC Cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC Cycles per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "Heap memory allocated" },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "Total current memory allocated" },
    {
     "expr": "go_memstats_sys_bytes",
     "legendFormat": "Total memory the Go runtime has claimed from the OS for everything"
    },
    {
     "expr": "go_memstats_sys_bytes - go_memstats_heap_sys_bytes",
     "legendFormat": "Non-Heap Overhead"
    },
    {
     "expr": "go_memstats_heap_sys_bytes - go_memstats_heap_alloc_bytes",
     "legendFormat": "Heap Fragmentation + Waste"
    }
   ]
  },
  {
   "title": "Memory Footprint Ratios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes / go_memstats_sys_bytes",
     "legendFormat": "Memory Efficiency"
    },
    {
     "expr": "(go_memstats_sys_bytes - go_memstats_heap_sys_bytes) / go_memstats_sys_bytes",
     "legendFormat": "Non-Heap Overhead"
    },
    {
     "expr": "go_memstats_heap_idle_bytes / go_memstats_sys_bytes",
     "legendFormat": "Idle Heap"
    },
    {
     "expr": "((go_memstats_sys_bytes - go_memstats_heap_released_bytes) / go_gc_gomemlimit_bytes * 100)\n  and\n(go_gc_gomemlimit_bytes != 9223372036854775807)",
     "legendFormat": "Memory Limit Used"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "((go_memstats_sys_bytes - go_memstats_heap_released_bytes) / go_gc_gomemlimit_bytes * 100)\n  and\n(go_gc_gomemlimit_bytes != 9223372036854775807)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stop-the-world Average Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}